Results of thread_exception_test:
common.threads.Thread1: Operation failed
    at ::run
