Results of exception_test:
exception: Invalid argument <x> at foo<-some_function
exception: Invalid argument <x>='hello world' at foo<-some_function
exception: Invalid argument <x>=-1 at foo<-some_function
exception: Invalid argument <x>=1 at foo<-some_function
exception: Invalid argument <x>=3.14 at foo<-some_function
exception: Argument <x> is out of range at foo<-some_function
exception: Argument <x>=0 is out of range [1;2) at foo<-some_function
exception: Argument <x>=0 is out of range [-2;-1) at foo<-some_function
exception: Argument <x>=3.14 is out of range [0;1) at foo<-some_function
exception: Argument <x>=5 is out of range [0;4) at foo<-some_function
exception: Null argument <ptr> at foo<-some_function
exception: Method 'foo' doesn't implemented at some_function
