Results of thread_exception_test:
system.threads.Thread1: Operation failed
    at ::run
