Results of action_queue_test:
-- perform test --
push action to thread 0
push action to thread 0
push action to thread 0
pop action from thread 0
time=00, action:
  action 1 executed
  callback 1
  wait 100 milliseconds
  wait: true
  after perform action: completed
time=01, action: empty
pop action from thread 0
time=02, action:
  exception: Exception occured during executing of action 2
    at action_handler
    at common::Action::Perform
  after perform action:
pop action from thread 0
time=03, action:
  action 3 executed
  wait 100 milliseconds
  wait: false
  after perform action:
pop action from thread 0
time=04, action:
  action 3 executed
  wait 100 milliseconds
  wait: false
  after perform action:
pop action from thread 0
time=05, action:
  action 3 executed
  wait 100 milliseconds
  wait: false
  after perform action:
pop action from thread 0
time=06, action:
  action 3 executed
  wait 100 milliseconds
  wait: false
  after perform action:
pop action from thread 0
time=07, action:
  action 3 executed
  wait 100 milliseconds
  wait: false
  after perform action: canceled
time=08, action: empty
time=09, action: empty
-- cleanup current thread --
exit
